// =====================================================
//  firebase.js  –  ERA Daily Routine Tracker
//  Firebase v9 Modular SDK – initialize ONCE here
// =====================================================

import { initializeApp }  from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth }        from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getDatabase }    from "https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";

// Reads from window.__ENV__ (generated by load-env.js) or falls back to your Firebase project config
const env = window.__ENV__ || {};

const getVal = (key) => env[`VITE_${key}`] || env[key];

const firebaseConfig = {
  apiKey:            getVal("FIREBASE_API_KEY")            || "AIzaSyARDz7eJC4F4yHOeHqH_yEzk_UexxiuwvU",
  authDomain:        getVal("FIREBASE_AUTH_DOMAIN")        || "era-daily-routine-tracker.firebaseapp.com",
  databaseURL:       getVal("FIREBASE_DATABASE_URL")       || "https://era-daily-routine-tracker-default-rtdb.firebaseio.com",
  projectId:         getVal("FIREBASE_PROJECT_ID")         || "era-daily-routine-tracker",
  storageBucket:     getVal("FIREBASE_STORAGE_BUCKET")     || "era-daily-routine-tracker.firebasestorage.app",
  messagingSenderId: getVal("FIREBASE_MESSAGING_SENDER_ID") || "725120609645",
  appId:             getVal("FIREBASE_APP_ID")             || "1:725120609645:web:fd4435d4ac6e3411b6fe64"
};

const app      = initializeApp(firebaseConfig);
export const auth     = getAuth(app);
export const database = getDatabase(app);
