// =====================================================
//  load-env.js  –  ERA Daily Routine Tracker
//  Reads .env (local) or process.env (Vercel/CI) and writes env-config.js
// =====================================================

const fs   = require("fs");
const path = require("path");

const envPath    = path.join(__dirname, ".env");
const outputPath = path.join(__dirname, "env-config.js");

const targetKeys = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_DATABASE_URL",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID"
];

const env = {};

if (fs.existsSync(envPath)) {
  // Local environment: read from .env file
  const lines = fs.readFileSync(envPath, "utf-8").split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const [key, ...rest] = trimmed.split("=");
    const k = key.trim();
    const v = rest.join("=").trim();
    env[k] = v;
  }
} else {
  // Remote environment (Vercel build): read from system process.env
  for (const baseKey of targetKeys) {
    const val = process.env[`VITE_${baseKey}`] || process.env[baseKey];
    if (val) {
      env[`VITE_${baseKey}`] = val;
      env[baseKey] = val;
    }
  }
}

// Write a browser-friendly JS file that sets window.__ENV__
const output = `// AUTO-GENERATED by load-env.js — DO NOT COMMIT THIS FILE
window.__ENV__ = ${JSON.stringify(env, null, 2)};
`;

fs.writeFileSync(outputPath, output, "utf-8");
console.log("✅  env-config.js generated successfully.");
