// =====================================================
//  load-env.js  –  ERA Daily Routine Tracker
//  Reads .env and writes env-config.js for the browser
//
//  Run once before opening the app:
//    node load-env.js
// =====================================================

const fs   = require("fs");
const path = require("path");

const envPath    = path.join(__dirname, ".env");
const outputPath = path.join(__dirname, "env-config.js");

if (!fs.existsSync(envPath)) {
  console.error("❌  .env file not found. Copy .env.example → .env and fill in your values.");
  process.exit(1);
}

// Parse KEY=VALUE lines (skip comments and blank lines)
const lines = fs.readFileSync(envPath, "utf-8").split(/\r?\n/);
const env   = {};

for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const [key, ...rest] = trimmed.split("=");
  env[key.trim()] = rest.join("=").trim();
}

// Write a browser-friendly JS file that sets window.__ENV__
const output = `// AUTO-GENERATED by load-env.js — DO NOT COMMIT THIS FILE
window.__ENV__ = ${JSON.stringify(env, null, 2)};
`;

fs.writeFileSync(outputPath, output, "utf-8");
console.log("✅  env-config.js generated successfully.");
